### ISSUE TITLE
Objektarten werden nicht importiert, wenn OGR diese als GeometryCollection erkennt

### ISSUE THREAD

**Issue by pathmapper** [kreis-viersen/xplan-reader#1]
Gemeldet von XLeitstelle:

> Die Konfiguration erfolgt über die gfs-Datei, die der gml-Treiber beim ersten einlesen automatisch erzeugt. Hier muss der Geometrietyp „7“ durch „0“ ersetzt werden.  
> 
>  
> 
> <Name>RP_Energieversorgung</Name>
> 
>     <ElementPath>RP_Energieversorgung</ElementPath>
> 
>     
> 
>     <GeometryType>7</GeometryType>
> 
>  
> 
> The <GeometryType> element can be specified to force the geometry type. Accepted values are : 0 (any geometry type), 1 (point), 2 (linestring), 3 (polygon), 4 (multipoint), 5 (multilinestring), 6 (multipolygon), 7 (geometrycollection).

Möglicher Fix in https://github.com/kreis-viersen/xplan-reader/commit/f7d78355b68b7253a5e71374d288dd2398df8d4b.
>

**Comment by kraftto** [comment]
Wie wäre es, die kompletten GFS-Templates (ggf. je XPlanGML-Version) vorzugenerieren und mit dem Plugin auszuliefern? Damit könnte man auch die Feldtypen fest definieren, also z.B. StringList für mehrfach belegbare Attribute, auch wenn's im Instanzdokument nur einmal vorkommt (und dann als einfacher String interpretiert wird). Auch könnte man komplexe Attribute als solche kenntlich machen, z.B.
`
<PropertyDefn>
      <Name>gemeinde/gemeindeName</Name>
      <ElementPath>gemeinde|XP_Gemeinde|gemeindeName</ElementPath>
      <Type>StringList</Type>
    </PropertyDefn>
    <PropertyDefn>
      <Name>gemeinde/ortsteilName</Name>
      <ElementPath>gemeinde|XP_Gemeinde|ortsteilName</ElementPath>
      <Type>StringList</Type>
    </PropertyDefn>
`

**Comment by pathmapper** [comment]
> Wie wäre es, die kompletten GFS-Templates (ggf. je XPlanGML-Version) vorzugenerieren und mit dem Plugin auszuliefern?

Habe es gerade ausprobiert, technisch geht das, dass wir GFS-Templates ausliefern und beim Laden der XPlanGML verwenden. 
Finde ich auch einen gute Idee, wenn jemand mit entsprechendem KnowHow die GFS-Templates bereitstellen würde :-) Könnte die XLeitstelle das übernehmen?

> ggf. je XPlanGML-Version

Das wäre auch möglich, wir lesen bereits jetzt mit dem Plugin die XPlanGML-Version aus, so dass es kein Problem wäre, eine entsprechendes GFS-Template zu verwenden. 

---
Für den [OGR-NAS-Treiber](https://gdal.org/drivers/vector/nas.html) gibt es übrigens ein [GFS-Template](https://github.com/norBIT/alkisimport/blob/master/alkis-schema.gfs).

**Comment by kraftto** [comment]
Wir haben das schonmal als Erweiterung/Encoding Rule für [Shapechange](https://shapechange.net) diskutiert. Wenn es jetzt einen klaren Use Case gibt, können wir das voraussichtlich übernehmen.

**Comment by pathmapper** [comment]
> mit dem Plugin auszuliefern

Aktuell darf ein Plugin maximal 20 MB (gezippt) haben. Da haben wir noch reichlich Luft nach oben, aktuell sind wir bei 2,4 MB und da sind auch die XPlanBox-Stile (als SE und SLD) und SVG-Symbole mit dabei.

Selbst die 1,3 MB [alkis-schema.gfs](https://github.com/norBIT/alkisimport/blob/master/alkis-schema.gfs) ergibt gezippt nur 46 KB.
