### ISSUE TITLE
XPlanReader Export nach Esri

### ISSUE THREAD

**Issue by StadtGE** [kreis-viersen/xplan-reader#10]
Hallo,
gibt es eine Möglichkeit eines Exports samt aller Symboliken etc. nach Esri-Produkten?
Wenn ich die Layer als shape etc. speichere, bekomme ich leider die Symbolik nicht mit.
Eine Layerdefinitionsdatei in qis bringt mir in ArcGIS leider auch nichts.
Ich hoffe jemand kann mir weiter helfen.

Grüße
Eva

**Comment by pathmapper** [comment]
Guten Morgen,

das ist ja eher eine allgemeine Frage hinsichtlich des Transfers von QGIS Styles nach ESRI (ArcMap? ArcPro?).

Es gibt theoretisch die Möglichkeit die Styles per SLD zu übergeben. Praktisch wird ein vollständiger Export aber daran scheitern, dass 
- wir hier mehr Logik in den Styles haben, als mit SLD möglich ist
- der SLD-Export aus QGIS aktuell noch teilweise unvollständig ist (Alternative eventuell https://geostyler.org/)

Wenn das Einbinden eines WMS mit dem Plan in "Esri-Produkten" ausreicht, dann könnte man mit QGIS Server einen sochen WMS erstellen, welcher das Styling vom XPlanReader 1:1 verwendet.

Viele Grüße!
