### ISSUE TITLE
Georeferenzierte Rastergrafik eines Planwerkes

### ISSUE THREAD

**Issue by EZUSoft** [kreis-viersen/xplan-reader#8]
Vor allem in der Anfangsphase wird die teilvektorisierte Variante mit Geltungsbereich und georeferenzierter Rastergrafik des Planwerkes überwiegen.
Aktuell scheint das "Einhängen" des georeferenzierten Planes durch den XPlan-Reader nicht vorgesehen.
Ist in dieser Richtung etwas geplant?

**Comment by pathmapper** [comment]
Bisher ist da nichts in die Richtung geplant, aber wir schauen uns das gerne 'mal an - danke für die Anregung!

Die Referenz auf Rasterpläne in der XPlanGML kann ja ganz unterschiedlich sein, z.B. lokale absolute und relative Pfade, `https` und in der Spezifikation steht sogar etwas von WMS...

Dazu gibt es noch Unterschiede zwischen den XPlanGML-Versionen, was die Referenzierung betrifft + viele verschiedene Rasterformate...

Bisher sind mir Rasterdaten bewusst nur bei den [XPlanArchiven](https://gitlab.opencode.de/diplanung/ozgxplanung/-/tree/main/xplan-documentation/xplan-benutzerhandbuch/src/main/asciidoc#xplanarchiv) der XPlanBox aufgefallen, da liegt der Rasterplan auf gleicher Ebene neben der XPlanGML. 

Wo liegen denn bei Euch die Rasterpläne?

**Comment by EZUSoft** [comment]
Wir "schnüren" ein Dateipaket, dh. der Rasterplan ist Bestandteil des ZIP-Archivs. Für QGIS selbst sollte es dann  relativ egal sein ob GeoTIFF oder mit Einpassdatei.
In den XPlan Testdaten [https://bitbucket.org/geowerkstatt-hamburg/xplan-testdaten/src/master/](url) sind ja auch fast alle Archive so aufgebaut (gml + png/pgw).

**Comment by pathmapper** [comment]
Wir haben das jetzt 'mal intern diskutiert und sind zu dem Ergebnis gekommen, dass der XPlan-Reader eventuell referenzierte Rasterpläne nicht laden sollte.

Wir sind mit dem XPlan-Reader angetreten um XPlanGML zu visualisieren. Referenzierte Rasterpläne sind dort nur als Attributwert vorhanden. 
Der eigentliche Blocker für uns ist aber, dass wir nicht sicherstellen können, dass die referenzierten Rasterpläne auch geladen werden, z.B. 
- kann es sein, dass die referenzierte Datei nicht am angegebenen Ort liegt
- der Rasterplan liegt im proprietären ECW-Format vor und das verwendete QGIS läuft ohne ECW-Treiber
- der referenzierte Plan liegt im Internet, aber es wird offline gearbeitet
- das Worldfile hat Fehler
- ...

Für User wird das dann nicht immer nachvollziehbar sein, warum ein Rasterplan technisch nicht geladen werden konnte und womöglich ist dann der XPlan-Reader schuld :-)

Liegt ein Rasterplan vor, kann dieser ganz einfach per Drag'n'Drop in QGIS importiert werden.

Aktuell kann man in den Attributen des Layers `*_Bereich` nachschauen, ob es Referenzen auf Rasterpläne gibt.
Vielleicht zeigen wir das zukünftig prominenter an, z.B. in der "Planinfobox" neben den diversen anderen Infos. 

/cc @stoni100

**Comment by EZUSoft** [comment]
Vielen Dank für die schnelle Reaktion.
Ich schau mal was ich damit umgehe.

Bleibt am Ball :-)

**Comment by stoni100** [comment]
Mit der neuesten Version der Styles wird zumindest angezeigt, ob Rasterdateien vorhanden sind.

Aktuell aber nur für eine 1:1 Variante, d.h. 1 BP-Plan = 1 BP_Bereich = 1 Rasterdatei.
Andere Beispiele habe ich zur Zeit nicht, würde mich aber freuen, welche zu bekommmen :-) (open@kreis-viersen.de)

Zum probieren 

Styles aus der Zip-Datei unter https://opendata-kreis-viersen.de/QGIS/XPLAN-Reader/styles13(1)-01.zip nach 

C:\Users\%USERNAME%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\xplan-reader\styles

kopieren und vorhandene überschreiben
![Reader_Plan_mit_raster](https://user-images.githubusercontent.com/53898087/229029337-95bb7b24-53a9-42d1-9051-3cc713a7e1d6.jpg)

**Comment by pathmapper** [comment]
@EZUSoft mit der Version `v0.16.0` wird jetzt auch die Anzahl der Rasterpläne in der Infobox angezeigt.

So bekommt ein User direkt einen Hinweis, dass es referenzierte Rasterpläne gibt und kann dann bei Interesse z.B. in `BP_Bereich` oder `XP_Rasterdarstellung` nachschauen, was für Rasterpläne referenziert sind.

Weitergehende Funktionalität ist aus den oben im Issue genannten Gründen aktuell nicht geplant.

![grafik](https://github.com/kreis-viersen/xplan-reader/assets/20856381/c78e11a8-24bb-4b4c-84fb-05bb17a8a6ed)
